feeds_filepath: feeds.json
last_run: 1763370658.747367
last_run_format: 2025-11-17 10:10
logs_filepath: logs.json
project_name: RSS to Todoist
todoist:
  music_project_id: 2337470474
  podcast_project_id: 2336934528
  youtube_project_id: 2337470496
version: 1.0
