feeds_filepath: feeds.json
last_run: 1736907994.160171
last_run_format: 2025-01-15 03:26
logs_filepath: logs.json
project_name: RSS to Todoist
todoist:
  music_project_id: 2337470474
  podcast_project_id: 2336934528
  youtube_project_id: 2337470496
version: 1.0
