feeds_filepath: feeds.json
last_run: 1767568070.943585
last_run_format: 2026-01-05 00:07
logs_filepath: logs.json
project_name: RSS to Todoist
todoist:
  music_project_id: 2337470474
  podcast_project_id: 2336934528
  youtube_project_id: 2337470496
version: 1.0
