feeds_filepath: feeds.json
last_run: 1771050067.324615
last_run_format: 2026-02-14 07:21
logs_filepath: logs.json
project_name: RSS to Todoist
todoist:
  music_project_id: 2337470474
  podcast_project_id: 2336934528
  youtube_project_id: 2337470496
version: 1.0
