feeds_filepath: feeds.json
last_run: 1726623246.206383
last_run_format: 2024-09-18 03:34
logs_filepath: logs.json
project_name: RSS to Todoist
todoist:
  music_project_id: 2337470474
  podcast_project_id: 2336934528
  youtube_project_id: 2337470496
version: 1.0
